name: Vercel Deployment

# Set environment variables required for Vercel Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

# Trigger deployment on push to the 'main' or 'master' branch 
on:
  push:
    branches:
      - main
      - master

# Defines the job to deploy 
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
     # Step 1: Checkout the code from the repository
      - uses: actions/checkout@v2

      # Step 2: Install the latest version of the Vercel CLI globally
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      # Step 3: Pull environment configuration from Vercel 
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      # Step 4: Build project artifacts using Vercel CLI
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      # Step 5: Deploy the built project to Vercel   
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}